apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: starlight-view-modes-overwork
  namespace: starlight-view-modes-overwork
spec:
  secretName: starlight-view-modes-overwork
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  dnsNames:
    - "starlight-view-modes-overwork.trueberryless.org"
